language: php
php:
  - 7.1
cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script:
  - composer phpunit

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/clover.xml; fi
 - composer phpcs fi